# Generated by Django 5.2.2 on 2025-06-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chauffeur_vehicule_remove_client_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nom_complet',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
