# Generated by Django 5.2.2 on 2025-06-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='nom',
        ),
    ]
