import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ✅ IMPORT Navbar
import { Navbar } from "../components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KSR Location",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ✅ On insère la navbar ici */}
        <Navbar />
        

        {children}
        <footer className="bg-gray-200 text-center py-6 mt-12">
          <p className="text-gray-700">© 2025 KSR Location. Tous droits réservés.</p>
        </footer>
      </body>
    </html>
  );
}
